### ISSUE TITLE
Quick Refresher

### ISSUE THREAD

**Issue by pGit1** [titu1994/Snapshot-Ensembles#10]
@titu1994 

For a quick refresher does the the Cosine Scheduler start from the initial lr (alpha zero) and increase learning rate or does it start from some high learning rate and go down to alpha zero?
  
EDIT: I think it is the later. It starts at alpha_zero drops and returns back to original alpha. So if alpha zero is .01 it the learning rate would oscillate between .01 and 0

**Comment by titu1994** [comment]
The second option. It starts at alpha_zero and approaches a value close to zero, but not exactly zero, then increases to alpha zero again.

**Comment by pGit1** [comment]
Dude you are SUPER helpful...THANK YOU!

I have a **BURNING** question for you though. How exactly are you able to read...comprehend...and implement so many papers? 

Is it because you have God given olympiad level intelligence/math/development skills (im fine if this is your answer) or is it becuase you studied some math book or coding book that gave you these abilities? Frankly I have a hard enough time following the math in papers let alone thinking about an implementation. Please advise...

Thanks again!

**Comment by pGit1** [comment]
Also is this on your radar? Seems like a memory hog...

https://openreview.net/pdf?id=S18Su--CW
