### ISSUE TITLE
Alpha Zero

### ISSUE THREAD

**Issue by pGit1** [titu1994/Snapshot-Ensembles#11]
@titu1994 

Does Alpha Zero in the callback overwrite LR in the optimizer once you compile? If LR of my optimizer is set to .1 and alpha_zero is set to .0001 how is this handled? Right now I am changing LRs in two places just wondering if that is necessary.

**Comment by titu1994** [comment]
This callback overwrites the learning rate of the optimizer, since this is based off the LearningRateScheduler which overrides the optimizers LR.

**Comment by pGit1** [comment]
Thanks!!
