### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by pGit1** [titu1994/Snapshot-Ensembles#2]
When I run this code:

`snapshot = SnapshotCallbackBuilder(T=nb_epoch,M=5,alpha_zero=0.01)

model.fit(X_train[:5000], Y_train[:5000], batch_size=batch_size, nb_epoch=nb_epoch, verbose=1,
          callbacks=[snapshot.get_callbacks()],
          validation_data=(X_test, Y_test))`

I get this error:

`AttributeError                            Traceback (most recent call last)
<ipython-input-66-47cb6b81962c> in <module>()
     31 model.fit(X_train[:5000], Y_train[:5000], batch_size=batch_size, nb_epoch=nb_epoch, verbose=1,
     32           callbacks=[snapshot.get_callbacks()],
---> 33           validation_data=(X_test, Y_test))
     34 score = model.evaluate(X_test, Y_test, show_accuracy=True, verbose=0)
     35 print('Test score:', score[0])

/python2.7/site-packages/keras/models.pyc in fit(self, x, y, batch_size, nb_epoch, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, **kwargs)
    595                               shuffle=shuffle,
    596                               class_weight=class_weight,
--> 597                               sample_weight=sample_weight)
    598 
    599     def evaluate(self, x, y, batch_size=32, verbose=1,

/python2.7/site-packages/keras/engine/training.pyc in fit(self, x, y, batch_size, nb_epoch, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight)
   1105                               verbose=verbose, callbacks=callbacks,
   1106                               val_f=val_f, val_ins=val_ins, shuffle=shuffle,
-> 1107                               callback_metrics=callback_metrics)
   1108 
   1109     def evaluate(self, x, y, batch_size=32, verbose=1, sample_weight=None):

/python2.7/site-packages/keras/engine/training.pyc in _fit_loop(self, f, ins, out_labels, batch_size, nb_epoch, verbose, callbacks, val_f, val_ins, shuffle, callback_metrics)
    785             callback_model = self
    786 
--> 787         callbacks._set_model(callback_model)
    788         callbacks._set_params({
    789             'batch_size': batch_size,

/python2.7/site-packages/keras/callbacks.pyc in _set_model(self, model)
     27     def _set_model(self, model):
     28         for callback in self.callbacks:
---> 29             callback._set_model(model)
     30 
     31     def on_epoch_begin(self, epoch, logs={}):

AttributeError: 'list' object has no attribute '_set_model'
`

**Comment by titu1994** [comment]
That's a bug. Try removing the square brackets around callbacks and make it : callbacks=snapshot.get_callbacks()

I guess it's passing a list into a list so it's not able to find the callbacks

**Comment by pGit1** [comment]
@titu1994 thanks for this suggestion!! I just did that prior to reading this and it worked. Training progression kicked off. However upon running I get a new error now at the end of the second epoch:

`IOError: Unable to create file (Unable to open file: name = 'weights/model-1.h5', errno = 2, error message = 'no such file or directory', flags = 13, o_flags = 602)`

I am not sure how to remedy this one. I was able to get the first fix by more closely following your code.

**Comment by titu1994** [comment]
@pGit1 Ah thats another bug. You'll need to create a directory named 'weights' in the root directory of the place where the model is being trained. I will be fixing that in an incoming commit.

**Comment by titu1994** [comment]
@pGit1 Are you using the latest code? These bugs were fixed quite some time ago.

**Comment by pGit1** [comment]
@titu1994 I just pulled the latest code from your master branch! It works perfectly now! Dude you are amazing. How did you learn how to code like this? 

Awesome job man! I answered my own question regarding little "t" as well by the way.

**Comment by pGit1** [comment]
We can close this now, but for the life of me I cannot figure out what little "t" represents in the cosine annealing function. If big T is "epoch" in our case what is little "t"?

**Comment by titu1994** [comment]
Big T is the total number of Epochs. Small t is like a time parameter which ranges from 0 to T

**Comment by pGit1** [comment]
I notice what may be an implementation issue with the cosine annealer. The current implementation seems to take the Floor of T and M and not the ceiling. 

`    def _cosine_anneal_schedule(self, t):
        cos_inner = np.pi * (t % (self.T // self.M))  # t - 1 is used when t has 1-based indexing.
        cos_inner /= self.T // self.M
        cos_out = np.cos(cos_inner) + 1
return float(self.alpha_zero / 2 * cos_out)`

I thought this syntax "//" in python is floor division? The equation in the paper takes a ceiling. Did you take the floor purposefully for other reasons?

https://github.com/titu1994/Snapshot-Ensembles/blob/master/images/cosine%20annealing%20schedule.JPG?raw=true

**Comment by titu1994** [comment]
That is due to the implementation. They assume small t starts with 1 based indexing. In python small t starts from 0 based indexing. 

You can plot the graph of cosine annealing with the implementation to see that the graph is exactly the same as that of the paper.

**Comment by pGit1** [comment]
Ahhhh. Touche' my friend. Thank you for your help!

**Comment by titu1994** [comment]
Np :D

**Comment by titu1994** [comment]
For the sake of completeness, the code to plot the cosine annealing curve (Using seaborn) : 

```
import seaborn as sns
sns.set_style('whitegrid', {'grid.linestyle': '--'})
import matplotlib.ticker as ticker
import numpy as np

T = 200
M = 5
alpha_zero = 0.1

def cosine_anneal_schedule(t):
    cos_inner = np.pi * (t % (T // M))  # t - 1 is used when t has 1-based indexing.
    cos_inner /= T // M
    cos_out = np.cos(cos_inner) + 1
    return float(alpha_zero / 2 * cos_out)

x = [i for i in range(T)]
y = [cosine_anneal_schedule(t_i) for t_i in x]

print('min :', np.min(y), 'max :', np.max(y))

sns.plt.plot(x, y)
ax = sns.plt.gca()
ax.xaxis.set_major_locator(ticker.MultipleLocator(T // M))
sns.plt.show()
```

Output:
![cosine annealing](https://cloud.githubusercontent.com/assets/3048602/20574507/cce5f6be-b1da-11e6-9062-5a57a16bd979.png)

**Comment by pGit1** [comment]
Thanks Titu. I had confirmed this as well when you said to plot it actually. Although my plot was not nearly as pretty as yours! :D 

`import matplotlib.pyplot as plt`
`import numpy as np`
`%matplotlib inline`

`def cosine_anneal_schedule(t,T,M,alpha_zero):`
    `cos_inner = np.pi * (t % (T // M))  # t - 1 is used when t has 1-based indexing.`
    `cos_inner /= T // M`
    `cos_out = np.cos(cos_inner) + 1`
    `return float(alpha_zero / 2 * cos_out)`

`bigt = 200
M = 5
g = []
for i in range(bigt):
    g.append(cosine_anneal_schedule(i,bigt,M,.1))
plt.plot(g)`

![index](https://cloud.githubusercontent.com/assets/13975114/20575971/c110ef5c-b189-11e6-922a-079181e704b2.png)

Not sure how to get my code to stack up the way yours does though.

**Comment by titu1994** [comment]
The code to stack up the x axis at the correct intervals is : 
```
import matplotlib.ticker as ticker
...
ax = plt.gca()
ax.xaxis.set_major_locator(ticker.MultipleLocator(T // M))
```

**Comment by pGit1** [comment]
@titu1994  is there a way to adjust Snapshot so I can string it together with other callbacks? It is all or nothing at the moment :( The brackets still cause an issue even with the latest code.

**Comment by titu1994** [comment]
The callback builder returns a list, you can simply append more callbacks to that list. Note however that learning rate and cannot be added again, as it is already being used. Same for model checkpoint. 

I don't understand what you mean by the brackets issue.

**Comment by pGit1** [comment]
For instance how would I use Early Stopping callback with Snapshot? Keras expects code like `callbacks=[EarlyStopping(),snapshot.get_callbacks()]` in order to have both callbacks work at the same time. This will error out though when using snapshot but works fine with other native Keras callbacks.

**Comment by titu1994** [comment]
@pGit1 Try this : 
```
callback_list = snapshot.get_callbacks()
callback_list.append(EarlyStopping(...))
...
model.fit(..., callbacks=callback_list)
```

**Comment by pGit1** [comment]
Amazing thanks!!

**Comment by pGit1** [comment]
@titu1994 

Unrelated:

Need your help implementing UnitBox---https://arxiv.org/pdf/1608.01471v1.pdf- for Keras (at least the loss functions). Is this possible?

**Comment by titu1994** [comment]
Hmm I've read this paper. The loss itself is not that bad. But setting up the input to the layer correctly and then calculating the loss for backpropagation is not easy in Keras. 

Perhaps waiting for Tensorflow to be fully integrated with Keras is best, then you can use the fluidity of Tensorflow with Keras layers.

**Comment by pGit1** [comment]
Makes sense Titu thank you! Trying to create bounding boxes is hard in keras with limited compute power. Have you read this paper: https://arxiv.org/pdf/1604.07953.pdf? His concept of "Food Activation Map" seems like it could apply to other domains. It is an offshoot of CAM but the calculation is different. He says he implemented it in Keras but I could not find source code. Something like this could be helpful if could get working.

**Comment by titu1994** [comment]
Not seen that paper yet. I'm on spring break now so I'm taking a short break from studies. I'll read up on it and see if I an reimplement the paper

**Comment by pGit1** [comment]
Thx. Are you getting a PhD somewhere?

**Comment by pGit1** [comment]
@titu1994 with the advent of 2.0 would something like Unit Box be possible?

**Comment by titu1994** [comment]
2.0 is not enough. You need to wait for Keras to merge with Tensorflow first. I think RC0 has already launched so it's not that far off. 

In any case, I'm a bit busy with my college work so I won't be implementing any new paper for some time.

**Comment by pGit1** [comment]
OK thanks Titu.
