### ISSUE TITLE
Jupyter notebook error

### ISSUE THREAD

**Issue by AIAdventures** [titu1994/Snapshot-Ensembles#3]
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-14-6d847bb94061> in <module>()
      1 preds = []
      2 for fn in models_filenames:
----> 3     model.load_weights(fn)
      4     yPreds = model.predict(testX, batch_size=128)
      5     preds.append(yPreds)

/home/andrewcz/miniconda3/lib/python3.5/site-packages/keras/engine/topology.py in load_weights(self, filepath, by_name)
   2487         if h5py is None:
   2488             raise ImportError('`load_weights` requires h5py.')
-> 2489         f = h5py.File(filepath, mode='r')
   2490         if 'layer_names' not in f.attrs and 'model_weights' in f:
   2491             f = f['model_weights']

/home/andrewcz/miniconda3/lib/python3.5/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    270 
    271                 fapl = make_fapl(driver, libver, **kwds)
--> 272                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    273 
    274                 if swmr_support:

/home/andrewcz/miniconda3/lib/python3.5/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     90         if swmr and swmr_support:
     91             flags |= h5f.ACC_SWMR_READ
---> 92         fid = h5f.open(name, flags, fapl=fapl)
     93     elif mode == 'r+':
     94         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/pip-at6d2npe-build/h5py/_objects.c:2684)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/pip-at6d2npe-build/h5py/_objects.c:2642)()

h5py/h5f.pyx in h5py.h5f.open (/tmp/pip-at6d2npe-build/h5py/h5f.c:1930)()

OSError: Unable to open file (Unable to open file: name = 'weights/wrn-cifar100-16-4-best.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

**Comment by AIAdventures** [comment]
![image](https://cloud.githubusercontent.com/assets/26102503/26024604/0cf85152-3818-11e7-91dc-4215866f1e81.png)

**Comment by titu1994** [comment]
Download and extract the weights from the Release tab of the repository. Then run it.
