### ISSUE TITLE
AttributeError: 'list' object has no attribute 'set_model'

### ISSUE THREAD

**Issue by sedghi** [titu1994/Snapshot-Ensembles#4]
Thanks for the implementation, 
I'm getting the `AttributeError: 'list' object has no attribute 'set_model'` error while using this callback. any comments? 
I think it is because the return of SnapshotCallbackBuilder is a list of callbacks and I'm using other callbacks also

**Comment by titu1994** [comment]
How are you using this callback ? Can you post the code ?

**Comment by sedghi** [comment]
no worries, I was appending it to the main callback list which resulted in
 `[Callback1 , [SnapshotCallbacks2]] , ...]`
 which caused the problem. It is working great, thanks again

**Comment by ghost** [comment]
Im getting the same error with this code 

> history = model.fit_generator(generator_labels[gen_key],steps_per_epoch=80,epochs=10,validation_data=generator_val_labels[gen_key],validation_steps=30,callbacks=[lrop,ckpt,es])

es Is early stopping 
ckpt is model checkpoint 
and lrop is ReduceLearningRateOnPlateou

It seems that i cant use lrop togetehr with the other callbacks when i try it alone it works... any ideas ?
